language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"
# command to install dependencies
install: "pip install -e ."
addons:
  postgresql: "9.4"
before_script:
  - psql -c "CREATE USER test WITH password 'test';" -U postgres
  - psql -c "CREATE DATABASE test_async_pg OWNER test;" -U postgres
script: ./run-tests