#!/bin/bash

export DB_USER=test
export DB_NAME=test_async_pg
export DB_PASSWORD=test
export LOG_LEVEL=debug

exec nosetests \
        --logging-format='%(asctime)s [%(name)s] %(levelname)-6s %(message)s' \
        --with-coverage \
        --cover-min-percentage=93 \
        --cover-package=tornado_psycopg2
